stages:
    - release

release:
    image: node:13
    stage: release
    only:
        refs:
        - master
        # This matches maintenance branches
        - /^(([0-9]+)\.)?([0-9]+)\.x/
        # This matches pre-releases
        - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ 
    script:
        - npm install @semantic-release/gitlab
        - npx semantic-release