stages:
    - release

release:
    image: node:13
    stage: release
    only:
        refs:
        - master
    script:
        - npm install @semantic-release/gitlab
        - npx semantic-release