stages:
    - release

release:
    image: node:13
    stage: release
    only:
        refs:
        - master
    script:
        - touch CHANGELOG.md
        - npm install @semantic-release/gitlab  @semantic-release/changelog
        - npx semantic-release
    artifacts:
        paths:
        - CHANGELOG.md