plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - - "@semantic-release/exec"
      - cmd: npm version ${nextRelease.version}
    - "@semantic-release/gitlab"
branches:
    - "master"